### ISSUE TITLE
Make sure to use 'getActivity()'

### ISSUE THREAD

**Issue by lidox** [lutvie72/RackMonthPicker#1]
Attention: 
``` RackMonthPicker monthPicker = new RackMonthPicker(getActivity())```
In my case, a crash was caused because I was passing View.getContext().getApplicationContext() as Context to the Builder. This was fixed by using getActivity() instead.

The exception:

`                                                                      java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:355)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:324)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:285)
                                                                          at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
                                                                          at android.support.v7.app.AlertController.installContent(AlertController.java:225)
                                                                          at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:257)
                                                                          at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
                                                                          at android.app.Dialog.show(Dialog.java:295)
                                                                          at com.rackspira.kristiawan.rackmonthpicker.RackMonthPicker$Builder.build(RackMonthPicker.java:136)
                                                                          at com.rackspira.kristiawan.rackmonthpicker.RackMonthPicker.show(RackMonthPicker.java:47)
                                                                          at com.artursworld.nccn.model.wizard.psychosocial.PastPsychoSocialStep$2.onClick(PastPsychoSocialStep.java:202)
                                                                          at android.view.View.performClick(View.java:5198)
                                                                          at android.widget.CompoundButton.performClick(CompoundButton.java:122)
                                                                          at android.view.View$PerformClick.run(View.java:21147)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by kal72** [comment]
thank you,.
